# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OroMuscles' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OroMuscles
  pod 'Charts'
  pod 'Auth0', '~> 2.4'
   
  target 'OroMusclesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OroMusclesUITests' do
    # Pods for testing
  end

end
